name: Deploy Worker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: cfut_uahUPMHSYXQp3EKpoQcmieydMgr0C69udF6r81IH8bb59451
          accountId: 7dedff92c0ba532f41ef1e1ce0322833
          command: deploy worker.js --name steep-firefly-eed5
