# wrangler.toml
name = "virus-proxy"
main = "worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VIRUS_PROXY_KV"
id = "11b68f79726c4ffca3be31f5144bc721"
preview_id = "11b68f79726c4ffca3be31f5144bc721"

# مسیر دقیق فایل اصلی رو مشخص کن
# اگه توی ریشه هست، همون worker.js کافیه
