# ================================================================
#  پیکربندی Wrangler برای Amir Nova Proxy
# ================================================================

name = "amir-nova-proxy"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NOVA_KV"
id = "fd12429938dc4fe2bf4b35448052e21e"

[triggers]
crons = ["0 */6 * * *"]
